name: pac_control_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - jax
  - ruptures
  - numexpr
  - optax
  - numpyro
  - arviz
  - numba
  - patsy
  - dill
  - pip
  - pip:
    - ssm@git+https://github.com/lindermanlab/ssm.git