name: pac_control_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - jax
  - flax
  - seaborn
  - ruptures
  - numexpr
  - optax
  - numpyro
  - arviz
  - mat73
  - numba
  - patsy
  - cython
  - dill
  - pip